"""ProReadyEngineer MVP Pydantic schemas.

This module contains all Pydantic schemas for request/response validation.
"""

# Base schemas
from app.schemas.base import (
    BaseSchema,
    IDSchema,
    ResponseSchema,
    TimestampSchema,
    PaginationParams,
    PaginatedResponse,
)

# Auth schemas
from app.schemas.auth import (
    LoginResponse,
    RegisterResponse,
    UserRegisterRequest,
    UserLoginRequest,
    TokenPairResponse,
    RefreshTokenRequest,
    PasswordForgotRequest,
    PasswordResetRequest,
    PasswordResetResponse,
    LogoutResponse,
    AuthMeResponse,
)

# User schemas
from app.schemas.user import (
    UserCreateRequest,
    UserUpdateRequest,
    UserRoleUpdateRequest,
    UserResponse,
    UserListResponse,
    UserSearchQuotaResponse,
)

# Provider schemas
from app.schemas.provider import (
    ProviderPublicResponse,
    ProviderSearchResult,
    ProviderClaimSearchRequest,
    ProviderClaimSearchResult,
    ProviderClaimCreateRequest,
    ProviderClaimResponse,
    ProviderMembershipResponse,
    ProviderProfileCreateRequest,
    ProviderProfileUpdateRequest,
    ProviderProfileResponse,
    TierEvaluationCreateRequest,
    TierEvaluationResponse,
    TierEvaluationAdminResponse,
)

# Search schemas
from app.schemas.search import (
    SearchQueryRequest,
    LLMStructuredOutput,
    SearchResultItem,
    SearchQueryResponse,
    DocumentUploadInitiateRequest,
    DocumentUploadInitiateResponse,
    DocumentUploadCompleteRequest,
    DocumentUploadCompleteResponse,
    SearchRequestLogResponse,
    SearchResponse,
    SearchResult,
)

# RFQ schemas
from app.schemas.rfq import (
    RFQCreateRequest,
    RFQUpdateRequest,
    RFQSubmitRequest,
    RFQResponse,
    RFQStatusResponse,
    RFQFileCreateRequest,
    RFQFileResponse,
    RFQFileUploadInitiateResponse,
    RFQMatchResponse,
    RFQDispatchBatchResponse,
    RFQDispatchResponse,
    RFQUnlockResponse,
    RFQUnlockStatusResponse,
    RFQTeaserResponse,
    RFQDetailForProviderResponse,
)

# Quote schemas
from app.schemas.quote import (
    QuoteCreateRequest,
    QuoteSubmitRequest,
    QuoteFileCreateRequest,
    QuoteFileResponse,
    QuoteProviderInfo,
    QuoteResponse,
    QuoteForCustomerResponse,
    QuoteForProviderResponse,
    QuoteListResponse,
    QuoteAcceptRequest,
    QuoteAcceptResponse,
    QuoteWithdrawRequest,
    QuoteWithdrawResponse,
)

# NDA schemas
from app.schemas.nda import (
    NDACheckoutRequest,
    NDACheckoutResponse,
    NDAResponse,
    NDACustomerStatusResponse,
    NDAProviderStatusResponse,
    NDASigningCompleteRequest,
    NDASigningCompleteResponse,
)

# Payment schemas
from app.schemas.payment import (
    PaymentCreateRequest,
    PaymentResponse,
    PaymentCheckoutResponse,
    BillingPortalResponse,
    SubscriptionCreateRequest,
    SubscriptionResponse,
    SubscriptionListResponse,
    WebhookEventResponse,
    WebhookReplayRequest,
    WebhookReplayResponse,
)

# Advertising schemas
from app.schemas.advertising import (
    AdSlotResponse,
    AdvertisementCreateRequest,
    AdvertisementUpdateRequest,
    AdvertisementResponse,
    AdvertisementPublicResponse,
    AdvertisementListResponse,
    AdAssetUploadInitiateRequest,
    AdAssetUploadInitiateResponse,
    AdAssetUploadCompleteRequest,
    AdAssetUploadCompleteResponse,
    SoftwareProvidersAdsResponse,
    FeaturedFirmsAdsResponse,
)

# Admin schemas
from app.schemas.admin import (
    AdminRFQListParams,
    AdminRFQListItem,
    AdminRFQListResponse,
    AdminRFQDetailResponse,
    AdminRFQStatusOverrideRequest,
    AdminRFQStatusOverrideResponse,
    AdminProviderClaimListParams,
    AdminProviderClaimListItem,
    AdminProviderClaimListResponse,
    AdminProviderClaimDetailResponse,
    AdminProviderClaimApproveRequest,
    AdminProviderClaimApproveResponse,
    AdminProviderClaimRejectRequest,
    AdminProviderClaimRejectResponse,
    AdminTierRequestListParams,
    AdminTierRequestListItem,
    AdminTierRequestListResponse,
    AdminTierRequestDetailResponse,
    AdminTierRequestApproveRequest,
    AdminTierRequestApproveResponse,
    AdminTierRequestRejectRequest,
    AdminTierRequestRejectResponse,
    AdminPaymentListParams,
    AdminPaymentListItem,
    AdminPaymentListResponse,
    AdminWebhookListParams,
    AdminWebhookListItem,
    AdminWebhookListResponse,
    AdminWebhookDetailResponse,
    AdminWebhookReplayResponse,
    AdminAdListParams,
    AdminAdListItem,
    AdminAdListResponse,
    AdminAdPauseRequest,
    AdminAdPauseResponse,
    AdminUserSuspendRequest,
    AdminUserSuspendResponse,
    AdminAuditLogListParams,
    AdminAuditLogListItem,
    AdminAuditLogListResponse,
)

__all__ = [
    # Base
    "BaseSchema",
    "IDSchema",
    "ResponseSchema",
    "TimestampSchema",
    "PaginationParams",
    "PaginatedResponse",
    # Auth
    "UserRegisterRequest",
    "UserLoginRequest",
    "TokenPairResponse",
    "RefreshTokenRequest",
    "PasswordForgotRequest",
    "PasswordResetRequest",
    "PasswordResetResponse",
    "LogoutResponse",
    "AuthMeResponse",
    # User
    "UserCreateRequest",
    "UserUpdateRequest",
    "UserRoleUpdateRequest",
    "UserResponse",
    "UserListResponse",
    "UserSearchQuotaResponse",
    # Provider
    "ProviderPublicResponse",
    "ProviderSearchResult",
    "ProviderClaimSearchRequest",
    "ProviderClaimSearchResult",
    "ProviderClaimCreateRequest",
    "ProviderClaimResponse",
    "ProviderMembershipResponse",
    "ProviderProfileCreateRequest",
    "ProviderProfileUpdateRequest",
    "ProviderProfileResponse",
    "TierEvaluationCreateRequest",
    "TierEvaluationResponse",
    "TierEvaluationAdminResponse",
    # Search
    "SearchQueryRequest",
    "LLMStructuredOutput",
    "SearchResultItem",
    "SearchQueryResponse",
    "DocumentUploadInitiateRequest",
    "DocumentUploadInitiateResponse",
    "DocumentUploadCompleteRequest",
    "DocumentUploadCompleteResponse",
    "SearchRequestLogResponse",
    # RFQ
    "RFQCreateRequest",
    "RFQUpdateRequest",
    "RFQSubmitRequest",
    "RFQResponse",
    "RFQStatusResponse",
    "RFQFileCreateRequest",
    "RFQFileResponse",
    "RFQFileUploadInitiateResponse",
    "RFQMatchResponse",
    "RFQDispatchBatchResponse",
    "RFQDispatchResponse",
    "RFQUnlockResponse",
    "RFQUnlockStatusResponse",
    "RFQTeaserResponse",
    "RFQDetailForProviderResponse",
    # Quote
    "QuoteCreateRequest",
    "QuoteSubmitRequest",
    "QuoteFileCreateRequest",
    "QuoteFileResponse",
    "QuoteProviderInfo",
    "QuoteResponse",
    "QuoteForCustomerResponse",
    "QuoteForProviderResponse",
    "QuoteListResponse",
    "QuoteAcceptRequest",
    "QuoteAcceptResponse",
    "QuoteWithdrawRequest",
    "QuoteWithdrawResponse",
    # NDA
    "NDACheckoutRequest",
    "NDACheckoutResponse",
    "NDAResponse",
    "NDACustomerStatusResponse",
    "NDAProviderStatusResponse",
    "NDASigningCompleteRequest",
    "NDASigningCompleteResponse",
    # Payment
    "PaymentCreateRequest",
    "PaymentResponse",
    "PaymentCheckoutResponse",
    "BillingPortalResponse",
    "SubscriptionCreateRequest",
    "SubscriptionResponse",
    "SubscriptionListResponse",
    "WebhookEventResponse",
    "WebhookReplayRequest",
    "WebhookReplayResponse",
    # Advertising
    "AdSlotResponse",
    "AdvertisementCreateRequest",
    "AdvertisementUpdateRequest",
    "AdvertisementResponse",
    "AdvertisementPublicResponse",
    "AdvertisementListResponse",
    "AdAssetUploadInitiateRequest",
    "AdAssetUploadInitiateResponse",
    "AdAssetUploadCompleteRequest",
    "AdAssetUploadCompleteResponse",
    "SoftwareProvidersAdsResponse",
    "FeaturedFirmsAdsResponse",
    # Admin
    "AdminRFQListParams",
    "AdminRFQListItem",
    "AdminRFQListResponse",
    "AdminRFQDetailResponse",
    "AdminRFQStatusOverrideRequest",
    "AdminRFQStatusOverrideResponse",
    "AdminProviderClaimListParams",
    "AdminProviderClaimListItem",
    "AdminProviderClaimListResponse",
    "AdminProviderClaimDetailResponse",
    "AdminProviderClaimApproveRequest",
    "AdminProviderClaimApproveResponse",
    "AdminProviderClaimRejectRequest",
    "AdminProviderClaimRejectResponse",
    "AdminTierRequestListParams",
    "AdminTierRequestListItem",
    "AdminTierRequestListResponse",
    "AdminTierRequestDetailResponse",
    "AdminTierRequestApproveRequest",
    "AdminTierRequestApproveResponse",
    "AdminTierRequestRejectRequest",
    "AdminTierRequestRejectResponse",
    "AdminPaymentListParams",
    "AdminPaymentListItem",
    "AdminPaymentListResponse",
    "AdminWebhookListParams",
    "AdminWebhookListItem",
    "AdminWebhookListResponse",
    "AdminWebhookDetailResponse",
    "AdminWebhookReplayResponse",
    "AdminAdListParams",
    "AdminAdListItem",
    "AdminAdListResponse",
    "AdminAdPauseRequest",
    "AdminAdPauseResponse",
    "AdminUserSuspendRequest",
    "AdminUserSuspendResponse",
    "AdminAuditLogListParams",
    "AdminAuditLogListItem",
    "AdminAuditLogListResponse",
]
